### ISSUE TITLE
sched_getaffinity attribute not available on all python distributions

### ISSUE THREAD

**Issue by AdamStuckert** [gatech-genemark/GeneMark-ETP#9]
Hello,

I have posted this as an issue on the [Braker3 GitHub page](https://github.com/Gaius-Augustus/BRAKER/issues/632#issuecomment-1607789471), but pinging you all too.

ProtHint relies on attribute `sched_getaffinity` which is not available on all python distributions, and is system specific. This causes failures in this pipeline.

**Comment by alexlomsadze** [comment]
Hello Adam,

Thank you for the info, and I apologize for the late response.

By default, ProtHints determines the maximum number of available threads and uses the detected value during the run.
Yes, on systems without "sched_getaffinity" in the "os" module, running ProtHint in defaults mode - without the optional parameter "--threads N > 0" - will lead to ProtHint failure.

I implemented the workaround and updated the ProtHint code:
https://github.com/gatech-genemark/ProtHint/commit/103304ce336e6487821eba19fb2f14cf18946e25

However, I am not sure that this issue is a contributing factor in the discussion here: [Braker3 GitHub page](https://github.com/Gaius-Augustus/BRAKER/issues/632#issuecomment-1607789471), 

GeneMark-ETP and BRAKER3 have a parameter for the number of threads. The default value in BRAKER3 is "--threads=1". BRAKER3 passes this parameter to GeneMark-ETP and ProtHint. ProtHint then skips the step that detects the number of available threads, and "sched_getaffinity" is never called. Thus, ProtHint and BRAKER3 cannot fail on "sched_getaffinity".

Something else leads to the reported program termination: [Braker3 GitHub page](https://github.com/Gaius-Augustus/BRAKER/issues/632#issuecomment-1607789471).
I will look into the reported above error.

Best,
Alex Lomsadze
